name: dbt CI/CD

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the workflow

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # You can specify the Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt  # Install dbt (or specify a particular version)

      - name: Navigate to dbt project directory
        run: |
          cd /home/ubuntu1234/Desktop/coding/data_pipeline_complete/my_dbt_project  # Change this to your project path

      - name: Run dbt models
        run: |
          dbt run  # Run dbt within the correct directory
